### ISSUE TITLE
Script changes photo modified date

### ISSUE THREAD

**Issue by chrissbarr** [Nicholas-Barr/SynologyPhotoTagger#1]
When the tagger.sh script runs, it changes the 'Date Modified' date/time for the photo it's running on.

This means that every file the script touches is modified every time it runs, which:

1. Means that the 'Date Modified' info is largely useless, as it is updated each day
2. Confuses any software tracking the state of the files, as it will think they're changed each day (for instance, Synology Hyper Backup)

Can the script be changed so that it doesn't modify the 'Date Modified' info whenever it runs?

**Comment by Nicholas-Barr** [comment]
This should be working now.

Please feel free to reopen this issue if there are any more problems.
